name: sokrio_people_pulse
description: "A new Flutter project for Sokrio People Pulse."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Dependency Injection
  get_it: ^7.6.6

  # Networking
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Security
  flutter_secure_storage: ^8.0.0
  package_info_plus: ^4.2.0
  crypto: ^3.0.3

  # Functional Programming (Error Handling)
  dartz: ^0.10.1

  # Data Class / Equality
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Local Database (Offline-first)
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3

  # Routing
  go_router: ^13.0.1

  # UI Helper
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1
  
  # Testing
  mockito: ^5.4.4
  build_test: ^2.1.7
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
